require('dotenv').config();

const {
  CLIENT_ID, CLIENT_SECRET, PORT, REFRESH_TOKEN, REDIS_HOST, REDIS_PORT, REDIS_PASSWORD,
} = process.env;

module.exports = {
  CLIENT_ID,
  CLIENT_SECRET,
  PORT,
  REFRESH_TOKEN,
  REDIS_HOST,
  REDIS_PORT,
  REDIS_PASSWORD,
};
